### ISSUE TITLE
Mycelial?

### ISSUE THREAD

**Issue by Boes-man** [ika-rwth-aachen/robotkube#4]
Hello, you're project is very interesting and useful. Thanks!

I have also been tracking Mycelial and thought it would be if interest to you?

[Mycelial Git](https://github.com/mycelial/mycelial)
[Mycelial](https://www.mycelial.com/technology-article/replacing-event-driven-messaging)

**Comment by bastilam** [comment]
I was not aware of it yet, thanks for letting us know about Mycelial. We will consider it in our further development.

**Comment by tbaums** [comment]
Greetings from Michael at Mycelial! @bastilam - LMK if you'd like to discuss further how our project might align with your goals!
